### ISSUE TITLE
Request Add 6.10 Rc kernel 

### ISSUE THREAD

**Issue by ryzendew** [sirlucjan/copr-linux-cachyos#11]
[Remove_OS-mlock-Function-nvidia.txt](https://github.com/sirlucjan/copr-linux-cachyos/files/15505339/Remove_OS-mlock-Function-nvidia.txt)
i would like to test the 6.10 rc kernel with this patch and was wondering if you could make that happen.

**Comment by TrixieUA** [comment]
Sorry but i cant build rc kernel versions with current spec file.
