### ISSUE TITLE
Fedora Workstation/Steam Deck - Internal display not turning off

### ISSUE THREAD

**Issue by dragon99919** [sirlucjan/copr-linux-cachyos#4]
Hi! I've tried to using this Kernel with Fedora Workstation 38 on Steam Deck (because of mentioned default support). My question is, could you please add proper internal screen turn-off? When using this kernel, or even default Fedora kernel for that matter, when you turn off the internal display while connected to dock, the screen still stays off, it's just displayed as black. That behavior is different in stock SteamOS or even Linux Mint for example, when turning off internal screen shuts it down completely.

**Comment by sirlucjan** [comment]
If you send the appropriate patches, I will try to add them. Perhaps it is also a config issue. You would have to help me do the research because I don't have anything to run tests on.

**Comment by dragon99919** [comment]
Sadly, I do not have any knowledge of working on Kernel like that. : D
But indeed having the hardware, I could help to do the research, just tell me what to do. : )

**Comment by sirlucjan** [comment]
So, in the near future I will do some research about kernels in steamOS and Linux Mint and look for a suitable patch/config. I'll let you know.

**Comment by dragon99919** [comment]
Great, will wait! Thanks!

**Comment by ptr1337** [comment]
> Hi! I've tried to using this Kernel with Fedora Workstation 38 on Steam Deck (because of mentioned default support). My question is, could you please add proper internal screen turn-off? When using this kernel, or even default Fedora kernel for that matter, when you turn off the internal display while connected to dock, the screen still stays off, it's just displayed as black. That behavior is different in stock SteamOS or even Linux Mint for example, when turning off internal screen shuts it down completely.

Hey :)

I don't think this is a Kernel Issue. You can simply put in your energy settings in KDE that your screen does not shut down.
Should be under:
Settings --> Power Management --> Energy Saving --> Screen Energy Saving

if you disable it, it should stop this behaviour

**Comment by dragon99919** [comment]
Some update regarding my own experiments...
It seems that the problem is indeed related to kernel only. I checked some kernels on both Linux Mint (using standard 5.15 LTS kernel and mainline ubuntu kernels) and Fedora (using standard lastest releases and 5.15 longterm from kwizart repo). In both cases when using 5.15 kernel my Deck screen shuts down normally, while in anything 6.x it goes black with backlight on.

**Comment by sirlucjan** [comment]
I'm sorry, I haven't had a chance to deal with this error yet - working two jobs (university lecturer + working for a company) gives me a solid workload. It seems to be some kind of regression in the kernel. Next week the 6.4 kernel will be coming to COPR (initially to the dev repo) - maybe you can find time to check it on 6.4?

**Comment by dragon99919** [comment]
No worries, there's infinite amount of time. : D
Will check it on 6.4 and give you the feedback!

**Comment by sirlucjan** [comment]
Kernel 6.4 will appear in the test repo:  https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos-dev/

**Comment by dragon99919** [comment]
Just checked it - 6.4 kernel from your dev repo still has this issue.

**Comment by sirlucjan** [comment]
We will have to look for a solution to this problem. Thanks for the feeback.

**Comment by andersrh** [comment]
Hi, Is this still an issue in the newer kernels?

**Comment by 1Naim** [comment]
just guess work on my part but it shouldn't be since the kernel includes handheld patches at the time of writing

**Comment by 1Naim** [comment]
Closing due to inactivitiy.
