### ISSUE TITLE
Error: Unable to find a match: uksmd

### ISSUE THREAD

**Issue by enielrodriguez** [sirlucjan/copr-linux-cachyos#8]
Unable to find uksmd.

Env:
Legion 5 15ACH6H
Fedora 39

`sudo dnf install uksmd`

```
Copr repo for kernel-cachyos-addons owned by bieszczaders                                                       3.1 kB/s | 1.5 kB     00:00    
No match for argument: uksmd
Error: Unable to find a match: uksmd
```

However, I do find a package called uksmd-rawhide. I actually installed it, and from then on the rest of the instructions were fine.

PS: Thank you for your work and time

**Comment by sirlucjan** [comment]
Use uksmd-rawhide. I had to separate the names, because Fedora 38 has procps-ng 3.X, while Fedora 39 has procps-ng 4.X, and it was impossible to solve it otherwise.
