### ISSUE TITLE
Removing kernel-modules-core breaks kargs on Silverblue/immutable spins

### ISSUE THREAD

**Issue by trgeiger** [sirlucjan/copr-linux-cachyos#9]
Removing kernel-modules-core as specified in the instructions breaks `rpm-ostree kargs` commands as it expects kernel-modules-core to exist. Installation of CachyOS kernel still works without removing that package.

**Comment by TrixieUA** [comment]
I have kernel-modules-core removed and `rpm-ostree kargs` works.

**Comment by trgeiger** [comment]
Maybe this is a change in f40, that's where I encountered the issue. Are you on f40?

**Comment by TrixieUA** [comment]
> Maybe this is a change in f40, that's where I encountered the issue. Are you on f40?

Yes im on f40.

**Comment by trgeiger** [comment]
This is no longer a problem for me either so must've just been some temporary issues.
